# Generated by Django 5.2 on 2025-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=255)),
                ('book_publisher', models.CharField(max_length=255)),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
